import type { LanguageData } from "./types";

export const commonPhrases: LanguageData[] = [
  {
    id: "1",
    tagalog: "Kumusta ka?",
    ilocano: "Kumustaka?",
    kapampangan: "Komusta ka?",
    bisaya: "Kumusta ka?",
    chabacano: "¿Cómo está?",
    ilonggo: "Kamusta ka?",
    bicolano: "Kumusta ka?",
  },
  {
    id: "2",
    tagalog: "Salamat",
    ilocano: "Agyamanak",
    kapampangan: "Salamat",
    bisaya: "Salamat",
    chabacano: "Gracias",
    ilonggo: "Salamat",
    bicolano: "Salamat",
  },
  {
    id: "3",
    tagalog: "Anong pangalan mo?",
    ilocano: "Ania ti naganmo?",
    kapampangan: "Nanung lagyu mu?",
    bisaya: "Unsay ngalan nimo?",
    chabacano: "¿Cual es tu nombre?",
    ilonggo: "Ano ang ngalan mo?",
    bicolano: "Ano an ngaran mo?",
  },
  {
    id: "4",
    tagalog: "Nasaan ang banyo?",
    ilocano: "Ayanna ti banyo?",
    kapampangan: "Nukarin ing banyu?",
    bisaya: "Hain ang banyo?",
    chabacano: "¿Donde el banyo?",
    ilonggo: "Diin ang banyo?",
    bicolano: "Saen an banyo?",
  },
  {
    id: "5",
    tagalog: "Magkano ito?",
    ilocano: "Sagmamano daytoy?",
    kapampangan: "Magkanu ini?",
    bisaya: "Tagpila kini?",
    chabacano: "¿Cuanto este?",
    ilonggo: "Tagpila ini?",
    bicolano: "Tagpira ini?",
  },
  {
    id: "6",
    tagalog: "Gusto ko nito",
    ilocano: "Kayatko daytoy",
    kapampangan: "BurI ke ini",
    bisaya: "Gusto ko ni",
    chabacano: "Quere yo este",
    ilonggo: "Gusto ko ini",
    bicolano: "Gusto ko ini",
  },
  {
    id: "7",
    tagalog: "Hindi ko alam",
    ilocano: "Saanko nga ammo",
    kapampangan: "Ali ke balu",
    bisaya: "Wala ko kabalo",
    chabacano: "No sabe yo",
    ilonggo: "Wala ko kabalo",
    bicolano: "Dai ko aram",
  },
  {
    id: "8",
    tagalog: "Gutom na ako",
    ilocano: "Mabisinakon",
    kapampangan: "Bisang na ku",
    bisaya: "Gigutom na ko",
    chabacano: "Ambri ya yo",
    ilonggo: "Gutom na ko",
    bicolano: "Gutom na ako",
  },
  {
    id: "9",
    tagalog: "Anong oras na?",
    ilocano: "Ania ti oras?",
    kapampangan: "Nanu nang oras?",
    bisaya: "Unsang orasa na?",
    chabacano: "¿Que hora ya?",
    ilonggo: "Ano na ang oras?",
    bicolano: "Anong oras na?",
  },
  {
    id: "10",
    tagalog: "Punta tayo doon",
    ilocano: "Inkatay diay",
    kapampangan: "Munta ta karin",
    bisaya: "Adto ta didto",
    chabacano: "Anda kita alla",
    ilonggo: "Malakat kita didto",
    bicolano: "Maduman kita duman",
  },
  {
    id: "11",
    tagalog: "Pagod na ako",
    ilocano: "Nabannogakon",
    kapampangan: "Mapagal na ku",
    bisaya: "Kapoy na ko",
    chabacano: "Cansao ya yo",
    ilonggo: "Kapoy na ko",
    bicolano: "Pagalon na ako",
  },
  {
    id: "12",
    tagalog: "Ingat ka",
    ilocano: "Agannadka",
    kapampangan: "Mag-ingat ka",
    bisaya: "Pag-amping",
    chabacano: "Cuidao",
    ilonggo: "Paghalong",
    bicolano: "Mag-ingat ka",
  },
  {
    id: "13",
    tagalog: "Mahal kita",
    ilocano: "Ay-ayatenka",
    kapampangan: "Kaluguran daka",
    bisaya: "Gihigugma ta ka",
    chabacano: "Quere yo contigo",
    ilonggo: "Palangga ta ka",
    bicolano: "Namumutan taka",
  },
  {
    id: "14",
    tagalog: "Aalis na ako",
    ilocano: "Umayakon",
    kapampangan: "Mako na ku",
    bisaya: "Lakaw na ko",
    chabacano: "Ya anda ya yo",
    ilonggo: "Malakat na ko",
    bicolano: "Mahali na ako",
  },
  {
    id: "15",
    tagalog: "Tulungan mo ako",
    ilocano: "Tulongannak",
    kapampangan: "Saupan mu ku",
    bisaya: "Tabangi ko",
    chabacano: "Ayuda conmigo",
    ilonggo: "Buligi ko",
    bicolano: "Tabangan mo ako",
  },
  {
    id: "16",
    tagalog: "Ano ito?",
    ilocano: "Ania daytoy?",
    kapampangan: "Nanu ini?",
    bisaya: "Unsa kini?",
    chabacano: "¿Que este?",
    ilonggo: "Ano ini?",
    bicolano: "Ano ini?",
  },
  {
    id: "17",
    tagalog: "Sino ka?",
    ilocano: "Sino ka?",
    kapampangan: "Ninu ka?",
    bisaya: "Kinsa ka?",
    chabacano: "¿Quien tu?",
    ilonggo: "Sin-o ka?",
    bicolano: "Siisay ka?",
  },
  {
    id: "18",
    tagalog: "Dito lang",
    ilocano: "Ditoy laeng",
    kapampangan: "Keti mu",
    bisaya: "Diri ra",
    chabacano: "Aqui na",
    ilonggo: "Diri lang",
    bicolano: "Digdi lang",
  },
  {
    id: "19",
    tagalog: "Oo",
    ilocano: "Wen",
    kapampangan: "Wa",
    bisaya: "Oo",
    chabacano: "Si",
    ilonggo: "Huo",
    bicolano: "Iyo",
  },
  {
    id: "20",
    tagalog: "Hindi",
    ilocano: "Saan",
    kapampangan: "Ali",
    bisaya: "Dili",
    chabacano: "No",
    ilonggo: "Indi",
    bicolano: "Dai",
  },
  {
    id: "21",
    tagalog: "Naiintindihan ko",
    ilocano: "Maawatanko",
    kapampangan: "Aintindian ke",
    bisaya: "Nakasabot ko",
    chabacano: "Entiende yo",
    ilonggo: "Naintindihan ko",
    bicolano: "Naiintindihan ko",
  },
  {
    id: "22",
    tagalog: "Hindi ko naiintindihan",
    ilocano: "Saanko a maawatan",
    kapampangan: "Ali ke aintindian",
    bisaya: "Wala ko kasabot",
    chabacano: "No entiende yo",
    ilonggo: "Wala ko nakaintindi",
    bicolano: "Dai ko naiintindihan",
  },
  {
    id: "23",
    tagalog: "Pakiulit",
    ilocano: "Ulitem man",
    kapampangan: "Ulitin mu",
    bisaya: "Balika",
    chabacano: "Repetir",
    ilonggo: "Liwata",
    bicolano: "Uliton mo",
  },
  {
    id: "24",
    tagalog: "Mabuti",
    ilocano: "Naimbag",
    kapampangan: "Mayap",
    bisaya: "Maayo",
    chabacano: "Bueno",
    ilonggo: "Maayo",
    bicolano: "Marhay",
  },
  {
    id: "25",
    tagalog: "Paalam",
    ilocano: "Kasta pay",
    kapampangan: "Mako na ku",
    bisaya: "Ayo-ayo",
    chabacano: "Adios",
    ilonggo: "Sige na",
    bicolano: "Paaram",
  },
  {
    id: "26",
    tagalog: "Tara na",
    ilocano: "Inkatay",
    kapampangan: "Mako na ta",
    bisaya: "Lakat na ta",
    chabacano: "Vamos ya",
    ilonggo: "Lakat na kita",
    bicolano: "Lakaw na kita",
  },
  {
    id: "27",
    tagalog: "Ano ang gagawin natin?",
    ilocano: "Ania ti aramidenta?",
    kapampangan: "Nanu ing gawan ta?",
    bisaya: "Unsay buhaton nato?",
    chabacano: "¿Que kita hace?",
    ilonggo: "Ano ang himuon ta?",
    bicolano: "Ano an gigibuhon ta?",
  },
  {
    id: "28",
    tagalog: "Gusto ko matulog",
    ilocano: "Kayatko ti maturog",
    kapampangan: "BurI kung matudtud",
    bisaya: "Gusto ko matulog",
    chabacano: "Quere yo durmi",
    ilonggo: "Gusto ko matulog",
    bicolano: "Gusto ko magturog",
  },
  {
    id: "29",
    tagalog: "Nasaan ang bahay mo?",
    ilocano: "Ayanna ti balaymo?",
    kapampangan: "Nukarin ing bale mu?",
    bisaya: "Hain ang balay nimo?",
    chabacano: "¿Donde tu casa?",
    ilonggo: "Diin ang balay mo?",
    bicolano: "Saen an harong mo?",
  },
  {
    id: "30",
    tagalog: "Kailan ka babalik?",
    ilocano: "Kaano ka nga agsubli?",
    kapampangan: "Kapilan ka mibalik?",
    bisaya: "Kanus-a ka mobalik?",
    chabacano: "¿Cuando tu volve?",
    ilonggo: "San-o ka mabalik?",
    bicolano: "Kasuarin ka mabalik?",
  },
  {
    id: "31",
    tagalog: "Masaya ako",
    ilocano: "Naragsakak",
    kapampangan: "Masaya ku",
    bisaya: "Malipayon ko",
    chabacano: "Feliz yo",
    ilonggo: "Malipayon ko",
    bicolano: "Maugma ako",
  },
  {
    id: "32",
    tagalog: "Ang ganda nito",
    ilocano: "Napintas daytoy",
    kapampangan: "Maganda ini",
    bisaya: "Nindot kini",
    chabacano: "Que bonito este",
    ilonggo: "Nami ini",
    bicolano: "Magayon ini",
  },
  {
    id: "33",
    tagalog: "Mainit",
    ilocano: "Napudot",
    kapampangan: "Mapali",
    bisaya: "Init",
    chabacano: "Caliente",
    ilonggo: "Mainit",
    bicolano: "Mainit",
  },
  {
    id: "34",
    tagalog: "Malamig",
    ilocano: "Nalamiis",
    kapampangan: "Marimla",
    bisaya: "Bugnaw",
    chabacano: "Frio",
    ilonggo: "Malamig",
    bicolano: "Maripot",
  },
  {
    id: "35",
    tagalog: "Gusto mo ba?",
    ilocano: "Kayatmo kadi?",
    kapampangan: "BurI mu?",
    bisaya: "Gusto ka?",
    chabacano: "¿Quere tu?",
    ilonggo: "Gusto mo?",
    bicolano: "Gusto mo?",
  },
  {
    id: "36",
    tagalog: "Pag-usapan natin",
    ilocano: "Pagsasaritaantayo",
    kapampangan: "Isipan ta",
    bisaya: "Atong istoryahan",
    chabacano: "Vamos conversa",
    ilonggo: "Istoryahan ta",
    bicolano: "Pag-ulayan ta",
  },
  {
    id: "37",
    tagalog: "Sundan mo ako",
    ilocano: "Surotemnak",
    kapampangan: "Tuntunan mu ku",
    bisaya: "Sunda ko",
    chabacano: "Sigue conmigo",
    ilonggo: "Sunda ko",
    bicolano: "Sundan mo ako",
  },
  {
    id: "38",
    tagalog: "Naiinip na ako",
    ilocano: "Nabannogakon",
    kapampangan: "Mababalot na ku",
    bisaya: "Gi-bore na ko",
    chabacano: "Aburrio ya yo",
    ilonggo: "Gakapoy na ko",
    bicolano: "Naiinip na ako",
  },
  {
    id: "39",
    tagalog: "Ang hirap naman",
    ilocano: "Narigat met",
    kapampangan: "Marakal",
    bisaya: "Lisod man",
    chabacano: "Bien dificil",
    ilonggo: "Pung-aw",
    bicolano: "Mairapot",
  },
  {
    id: "40",
    tagalog: "Walang anuman",
    ilocano: "Awan aniaman",
    kapampangan: "Walang anuman",
    bisaya: "Walay sapayan",
    chabacano: "De nada",
    ilonggo: "Wala sing anuman",
    bicolano: "Mayong anuman",
  },
  {
    id: "41",
    tagalog: "Ingat sa biyahe",
    ilocano: "Agannad ka iti panagbanniaga",
    kapampangan: "Mag-ingat ka king biyahe",
    bisaya: "Amping sa biyahe",
    chabacano: "Cuidao na biaje",
    ilonggo: "Paghalong sa biyahe",
    bicolano: "Mag-ingat sa biyahe",
  },
  {
    id: "42",
    tagalog: "Nakita mo ba?",
    ilocano: "Nakitam kadi?",
    kapampangan: "Ikita mu?",
    bisaya: "Nakakita ka?",
    chabacano: "¿Ya ve tu?",
    ilonggo: "Nakita mo?",
    bicolano: "Nahiling mo?",
  },
  {
    id: "43",
    tagalog: "Pagod ako sa trabaho",
    ilocano: "Nabannogak iti trabaho",
    kapampangan: "Mapagal ku king obra",
    bisaya: "Kapoy ko sa trabaho",
    chabacano: "Cansao yo na trabajo",
    ilonggo: "Kapoy ko sa obra",
    bicolano: "Pagalon ako sa trabaho",
  },
  {
    id: "44",
    tagalog: "Puwede ba?",
    ilocano: "Mabalin kadi?",
    kapampangan: "Pwede?",
    bisaya: "Pwede ba?",
    chabacano: "¿Puede ba?",
    ilonggo: "Pwede?",
    bicolano: "Pwede?",
  },
  {
    id: "45",
    tagalog: "Hindi ko sinasadya",
    ilocano: "Saanko a ninamnama",
    kapampangan: "Ali ke inisadya",
    bisaya: "Dili nako tuyo",
    chabacano: "No fue mi intencion",
    ilonggo: "Indi ko tinuyo",
    bicolano: "Dai ko tuyo",
  },
  {
    id: "46",
    tagalog: "Nasaan na sila?",
    ilocano: "Ayanna ida?",
    kapampangan: "Nukarin na la?",
    bisaya: "Hain na sila?",
    chabacano: "¿Donde ya sila?",
    ilonggo: "Diin na sila?",
    bicolano: "Saen na sinda?",
  },
  {
    id: "47",
    tagalog: "Ayos lang",
    ilocano: "Nasayaat laeng",
    kapampangan: "Ayus lang",
    bisaya: "Okay ra",
    chabacano: "Ta bien",
    ilonggo: "Okay lang",
    bicolano: "Ayos lang",
  },
  {
    id: "48",
    tagalog: "Ang galing mo!",
    ilocano: "Nalaingka!",
    kapampangan: "Magaling ka!",
    bisaya: "Maayo ka!",
    chabacano: "Bien galing tu!",
    ilonggo: "Galing mo!",
    bicolano: "Marhay ka!",
  },
  {
    id: "49",
    tagalog: "Kailangan ko umalis",
    ilocano: "Kasapulak a pumanaw",
    kapampangan: "Kailangan kung mako",
    bisaya: "Kinahanglan ko mo-lakaw",
    chabacano: "Necesita yo anda",
    ilonggo: "Kinahanglan ko maglakat",
    bicolano: "Kaipuhan ko nang maghali",
  },
  {
    id: "50",
    tagalog: "Magkita tayo ulit",
    ilocano: "Agkita tayo manen",
    kapampangan: "Mikit ta pasibayu",
    bisaya: "Magkita ta pag-usab",
    chabacano: "Vamos mira otro vez",
    ilonggo: "Magkita kita ta liwat",
    bicolano: "Magkilingan kita giraray",
  },
];
